/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WebFunnel {
    /**
    * api base url
    */
    'apiUrl': string;
    /**
    * api end point to get titles
    */
    'getInvitationInfo': string;
    /**
    * logo image path
    */
    'logoImgPath': string;
    /**
    * api end point to save data (mobile number and user token number)
    */
    'savePhoneNumber': string;
  }
}

declare global {


  interface HTMLWebFunnelElement extends Components.WebFunnel, HTMLStencilElement {}
  var HTMLWebFunnelElement: {
    prototype: HTMLWebFunnelElement;
    new (): HTMLWebFunnelElement;
  };
  interface HTMLElementTagNameMap {
    'web-funnel': HTMLWebFunnelElement;
  }
}

declare namespace LocalJSX {
  interface WebFunnel {
    /**
    * api base url
    */
    'apiUrl'?: string;
    /**
    * api end point to get titles
    */
    'getInvitationInfo'?: string;
    /**
    * logo image path
    */
    'logoImgPath'?: string;
    /**
    * api end point to save data (mobile number and user token number)
    */
    'savePhoneNumber'?: string;
  }

  interface IntrinsicElements {
    'web-funnel': WebFunnel;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'web-funnel': LocalJSX.WebFunnel & JSXBase.HTMLAttributes<HTMLWebFunnelElement>;
    }
  }
}


